Adding test for django 1.11 and django 2.2
eduNEXT/eox-theming pull request #25
Opened 2020-09-25 23:51 UTC by vad33r

- Addiing tests for django22

- Adding app_name in eox_theming/urls.py and update --fail-under

- Adding isort:skip_file and setup.cfg configuration

2020-09-28 15:53 UTC, andrey-canon requested changes
@vad33r  you can exclude the isort verification or fix everything instead of add an ugly skip tag in every file

2020-09-28 15:53 UTC, andrey-canon commented on Makefile
> +run-tests: test-python quality
add blanck space after this

2020-09-28 15:53 UTC, andrey-canon commented on eox_theming/__init__.py
> +    isort:skip_file
Remove all theses changes, ` isort:skip_file `

2020-09-28 15:53 UTC, andrey-canon commented on setup.cfg
> +known_first_party = eox_manage
eox_manage ???

2020-09-28 15:53 UTC, andrey-canon commented on setup.cfg
> +max-line-length = 125
We always set this to  120

2020-09-28 15:53 UTC, andrey-canon commented on setup.cfg
> +ignore = E501, W503, W291
why do you add this ??

2020-09-28 15:53 UTC, andrey-canon commented on setup.cfg
> +	useless-suppression,
Fix this instead of disabling

2020-09-28 15:53 UTC, andrey-canon commented on setup.cfg
> +	trailing-whitespace,
Fix this instead of disabling

2020-09-28 15:53 UTC, andrey-canon commented on requirements/base.in
> +djangorestframework
why did you remove futures and added djangorestframework

2020-10-06 17:03 UTC, vad33r commented on setup.cfg
> +max-line-length = 125
there is a line with 124 length

2020-10-06 17:56 UTC, andrey-canon commented on setup.cfg
> +max-line-length = 125
make it shorter

2020-10-06 20:46 UTC, morenol commented on requirements/base.in
>  futures==3.3.0; python_version < "3.0"
futures should go in constraints.txt

2020-10-06 20:47 UTC, morenol commented on Makefile
> +	sed '/^[dD]jango==/d;/^djangorestframework==/d;' requirements/test.txt > requirements/test.tmp
I think that this package does not use djangorestframework so we should not have that package in any of the requirement files.

2020-10-06 22:42 UTC, andrey-canon commented on eox_theming/edxapp_wrapper/backends/i_mako.py
> +"""
?

2020-10-06 23:22 UTC, andrey-canon commented on .circleci/config.yml
> +      - TOX_ENV: py<< parameters.python_version >>-<< parameters.django_version >>
?

2020-10-06 23:24 UTC, andrey-canon approved these changes

2020-10-06 23:37 UTC, merged