Add JS to template
eduNEXT/eox-theming pull request #29
Opened 2020-12-15 14:35 UTC by magajh

This PR allows adding custom scripts for each template.

For example: to add a specific script to the login template, add the path and the configurations of the script
to the settings.
`    "THEME_OPTIONS": {
        "scripts": {
            ".*/login": [
                {
                    "type": "external",
                    "src": "https://www.test.com/js/myScript1.js"
                },
                {
                    "type": "inline",
                    "content": "alert('This alert box was called with the onload event');"
                }`
The attributes that can be specified are:
-  type: to indicate whether is an 'external' or 'inline' script
- media_type : 'module' or  'text/javascript' 
The media_type attribute has  'text/javascript' as its default value.

If the script type is 'external', then is necessary to specify the 'src' attribute.
if the script type is 'inline', then the 'content' attribute must have the script.

2020-12-15 15:50 UTC, felipemontoya requested changes
Also, as a general note, we need some testing for this

2020-12-15 15:50 UTC, felipemontoya commented on eox_theming/theming/extra_scripts.py
> +                    raise_error_invalid_script('type')
This is too aggressive since the `raise_error_invalid_script` literaly raises an exception. Should you place an incorrect script configuration all page rendering will immediately fail.

I would enclose the whole block in a try catch and make sure we log the errors appropriately, but otherwise continue without breaking page rendering

2020-12-15 15:50 UTC, felipemontoya commented on eox_theming/theming/extra_scripts.py
> +def process_scripts(request):
request is a very heavy object. If you are only using it for the path_info, then pass the path_info string so this is much more simple to mock and test.

2020-12-15 15:54 UTC, felipemontoya commented
After I reviewed the Theme PR I noticed that you are creating two categories with different precedence. On the one hand all the externals will be loaded first and only then will we start loading the inline scripts.

I think we should maintain the order of the scripts regardless of their type.

2020-12-15 16:43 UTC, felipemontoya commented on eox_theming/theming/context_processor.py
> +from extra_scripts import process_scripts
When I tried this on my devstack it failed until I changed this line to:
```
from eox_theming.theming.extra_scripts import process_scripts
```

2020-12-15 17:26 UTC, mariajgrimaldi commented on eox_theming/theming/extra_scripts.py
> +    for key in common_attributes:
why not key, values so you can use values instead of common_attr[key]

2020-12-16 13:20 UTC, mariajgrimaldi commented on eox_theming/tests/theming/test_extra_scripts.py
> +
what about testing the helper functions?

2020-12-16 13:45 UTC, mariajgrimaldi commented on eox_theming/theming/extra_scripts.py
> +common_attributes = {'type': {'options': ['inline', 'external']},
could be this a setting that we change in the future?

2020-12-16 13:45 UTC, mariajgrimaldi commented on eox_theming/tests/theming/test_extra_scripts.py
> +            }]}
I would do something like:

```
       themingConfig_mock.return_value = {
           ".*/dashboard": [
               {
                 "src": "https://www.test-external-script.com/js/myScript1.js",
                 "type": "external",
                 "media_type": "text/javascript",
               },
           ],
       }
```

2020-12-16 20:43 UTC, magajh commented on eox_theming/theming/extra_scripts.py
> +                    raise_error_invalid_script('type')
@felipemontoya  this is solved now. When a script attribute is missing or is not a valid option, instead of raising an exception, it logs the error.

Here is an example 
`2020-12-16 15:20:37,113 ERROR 2821 [eox_theming.theming.extra_scripts] [user None] extra_scripts.py:40 - Script could not get loaded. 'type' attribute is missing or is an invalid option.
`

2020-12-16 20:50 UTC, felipemontoya approved these changes

2020-12-17 20:23 UTC, merged