perf: add redwood compatibility
eduNEXT/eox-theming pull request #55
Opened 2024-07-17 22:50 UTC by bra-i-am

## Description

This PR aims to upgrade the plugin and workflow requirements, update the README and make it clearer, and fix a bug with the `footer_override` rendering (Issue 9)[https://github.com/eduNEXT/eox-release/issues/9]

## Testing instructions

1. Create a redwood environment and install distro `pip install git+https://github.com/eduNEXT/tutor-contrib-edunext-distro`
2. Install `eox-tenant`, the testing themes and this version of `eox-theming`
``` yml
DISTRO_DEFAULT_SITE_THEME: test-1
DISTRO_EOX_THEMING_DPKG:
  domain: github.com
  index: git
  name: eox-theming
  path: eduNEXT
  private: false
  protocol: https
  repo: eox-theming
  variables:
    development:
      EOX_THEMING_CONFIG_SOURCES:
      - from_eox_tenant_microsite_v2
      - from_django_settings
    production:
      EOX_THEMING_CONFIG_SOURCES:
      - from_eox_tenant_microsite_v2
      - from_django_settings
  version: bc/redwood.compatibility
DISTRO_THEMES:
- domain: github.com
  name: ednx-test-themes
  path: eduNEXT
  protocol: ssh
  repo: ednx-test-themes
  version: master
DISTRO_THEMES_NAME:
- test-1
- test-2
- test-3
DISTRO_THEMES_ROOT: /openedx/themes
DISTRO_THEME_DIRS:
- /openedx/themes/ednx-test-themes/edx-platform
```
3. Clone the test themes folder with `tutor distro enable themes`
4. Add the testing themes running and init the environment running
```bash
tutor images build openedx
tutor local do init
tutor local start
```
6. Create a new tenant and add this info to the tenant configs:
``` json
{
    "EDNX_USE_SIGNAL": true,
    "ENABLE_AUTHN_MICROFRONTEND": false,
    "THEME_OPTIONS": {
        "scripts": {
            "/login": [
                {
                    "content": "alert('This is a test for the inline script');",
                    "type": "inline"
                }
            ]
        },
        "theme": {
            "grandparent": "test-3",
            "name": "test-1",
            "parent": "test-2"
        }
    },
    "course_org_filter": [
        "OpenedX"
    ],"footer_override": "<div style=\"width: 100%;\"><div style=\"position: relative; padding-bottom: 41.67%; padding-top: 0; height: 0;\"><iframe title=\"Footer X\" frameborder=\"0\" width=\"1200\" height=\"500\" style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%;\" src=\"https://view.genially.com/66464d3334225f0015c0dc0e\" type=\"text/html\" allowscriptaccess=\"always\" allowfullscreen=\"true\" scrolling=\"yes\" allownetworking=\"all\"></iframe> </div> </div>",
    "header_langselector": true,
    "header_links": [
        {
            "target": "_self",
            "txt": "Courses",
            "url": "/courses"
        },
        {
            "class": "mx-2",
            "target": "_self"
        }
    ],
    "released_languages": "en,vi,es-419"
}
```
7. Go to your admin panel and create a waffle flag `learner_home_mfe.enabled` with the property `Everyone` in false to disable the Authn MFE
8. To test that execute the test cases from [this file](https://docs.google.com/document/d/18urdJPitAu1lUBvYdQcGXm4WRDbKD2eDf4TTGgrlzZU/edit)
9. To test the solved bug:
10. 

## Additional information

Include anything else that will help reviewers and consumers understand the change.
- Does this change depend on other changes elsewhere?
- Any special concerns or limitations? For example: deprecations, migrations, security, or accessibility.
- Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions.

## Checklist for Merge

- [ ] Tested in a remote environment
- [ ] Updated documentation
- [ ] Rebased master/main
- [ ] Squashed commits

2024-07-19 21:10 UTC, BryanttV reviewed
Hi @bra-i-am, thank you for the PR! I will be reviewing it, but for now, I would like to propose to separate into different PRs according to the objective. As far as I can see there are 3 different issues, could you open 2 more? It seems more understandable that way, what do you think?

2024-07-19 21:53 UTC, BryanttV commented on eox_theming/__init__.py
> +__version__ = '7.1.1'
Why would it be a patch, and not a minor?

2024-07-19 21:53 UTC, BryanttV commented on requirements/constraints.txt
> +-c https://raw.githubusercontent.com/openedx/edx-platform/open-release/redwood.master/requirements/constraints.txt
Would we need all edx-platform constraints here? Wouldn't [common constraints](https://raw.githubusercontent.com/openedx/edx-lint/master/edx_lint/files/common_constraints.txt) alone be sufficient?

2024-07-19 21:55 UTC, dcoa commented on CHANGELOG.md
> +- **Sending wrong footer in the Wiki**: The issue occurred when only the template directory for the current theme was being returned. If this directory didn't exist, the default template was returned
```suggestion
- **Django templates were not found according to the THEME_OPTIONS definition**: The issue occurred because the function `get_template_sources`  only returns the directory for the current theme, then If this directory doesn't exist, the default template is returned instead ([issue #9](https://github.com/eduNEXT/eox-release/issues/9)). This problem was resolved by executing the `get_theme_template_sources` method from the `EoxThemeFilesystemLoader`, which retrieves the template directories not only for the current theme but also for its parent and grandparent themes.
```

2024-07-19 22:03 UTC, dcoa commented on README.rst
> +Eox theming is a plugin for `Open edX <https://github.com/openedx/edx-platform>`_, and part of the Edunext Open Extensiones (aka EOX) that provides a stable place from where to create and launch them
```suggestion
Eox theming is a plugin for `Open edX platform <https://github.com/openedx/edx-platform>`_, and part of the Edunext Open edX Extensions (aka EOX) that provides a series of tools to customize and launch themes.
```

2024-07-22 13:53 UTC, bra-i-am commented on requirements/constraints.txt
> +-c https://raw.githubusercontent.com/openedx/edx-platform/open-release/redwood.master/requirements/constraints.txt
I chose instead to use the Redwood constraints file because this one contains more required by eox-theming constraints and I saw it as a fancy way of putting them all at once... I started thinking that if something changes in the Open edX constraints and is not well-configured in our eox-theming code, the app could break

I'll write them manually better... what do you think?

2024-07-22 14:08 UTC, BryanttV commented on requirements/constraints.txt
> +-c https://raw.githubusercontent.com/openedx/edx-platform/open-release/redwood.master/requirements/constraints.txt
Yes, you are right. I would think it's better to just add the constraints we need manually.

2024-07-22 14:11 UTC, bra-i-am commented on eox_theming/__init__.py
> +__version__ = '7.1.1'
I was in a conflict indeed. In the end, I made a patch version because the change that I thought could require a minor one (the README change) was just a rewrite of some little information and a little setting complementation... the other ones are just a bugfix and a third-party dependency update

Would you favor bumping to a minor version instead?

2024-07-22 14:23 UTC, bra-i-am commented
Hi @BryanttV, thanks a lot for your feedback c:

> I would like to propose to separate into different PRs according to the objective

I took these 3 issues as part of this same PR because of the scope of a migration task that involves updating the dependencies, solving issues, and improving the docs. I think it is not necessary to split the PR (equally, the issues are not so unrelated) but I have neither a problem doing it. Please, let me know your thoughts after this

2024-07-22 17:10 UTC, BryanttV commented on CHANGELOG.md
> +## v7.1.1 - 2024-07-17
Should we add a description of redwood support?

2024-07-22 17:14 UTC, BryanttV commented on eox_theming/__init__.py
> +__version__ = '7.1.1'
Considering what you say, the patch would be fine for me.

2024-07-22 17:18 UTC, BryanttV commented on README.rst
> +       from lms.envs.common import _make_mako_template_dirs  # pylint: disable=import-error
An indentation is missing

2024-07-22 17:19 UTC, BryanttV commented
@bra-i-am, looking at it, I agree with leaving only one PR

2024-07-22 17:24 UTC, BryanttV commented on README.rst
> +.. note::
This would look great in RTD, but currently, GitHub doesn't render it correctly. I suggest modifying it or even (in another issue, maybe) using Markdown to display this type of note more elegantly.

2024-07-22 17:27 UTC, BryanttV commented on README.rst
> +| Redwood          | >= 7.0       |
Wouldn't `v7.1.1` be compatible with Redwood?

2024-07-22 17:35 UTC, BryanttV commented on README.rst
> +                "grandparent":"my-theme-3",
```suggestion
                "parent":"my-theme-2",
                "grandparent":"my-theme-3"
```

2024-07-22 19:30 UTC, BryanttV commented on CHANGELOG.md
> +- **Django templates were not found according to the THEME_OPTIONS definition**: The issue occurred because the function `get_template_sources` only returns the directory for the current theme, then
```suggestion
- **Django templates were not found according to the THEME_OPTIONS definition**: The issue occurred because the `get_theme_template_sources` method only returns the directory for the current theme, then if this directory doesn't exist, the default template is returned instead ([issue #9](https://github.com/eduNEXT/eox-release/issues/9)). This problem was resolved by executing the `get_theme_template_sources` method from the `EoxThemeFilesystemLoader`, which retrieves the template directories not only for the current theme but also for its parent and grandparent themes.
```

2024-07-22 21:20 UTC, dcoa commented on README.rst
> +Using Open edX devstack
We can get rid of devtack because this is not being supported anymore

2024-07-22 21:24 UTC, dcoa commented on README.rst
> +* From Lilac version Django 2.2 is not supported, you should use Django 3.2 and eox-tenant >=4.0.
Use emojis, please as the example here https://github.com/eduNEXT/eox-tenant/blob/master/README.rst?plain=1#L71

2024-07-22 21:25 UTC, dcoa commented on README.rst
> -**NOTE**: the current ``common.py`` works with Open edX lilac version.
Please just not get rid of this information, follow the example, https://github.com/eduNEXT/eox-tagging/blob/master/README.rst?plain=1#L54-L61

2024-07-23 14:05 UTC, magajh reviewed
Thank you @bra-i-am!

2024-07-23 14:05 UTC, magajh commented on README.rst
>          settings.COMPREHENSIVE_THEME_DIRS = [
@bra-i-am in this example of what should go in COMPREHENSIVE_THEME_DIRS, I think we should use a more general directory path, similar to what we did in: https://github.com/eduNEXT/eox-theming/pull/55/files#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR114

instead of 
```
    settings.COMPREHENSIVE_THEME_DIRS = [
        '/edx/src/themes/ednx-test-themes/edx-platform/',
    ]
```
something like
```
    settings.COMPREHENSIVE_THEME_DIRS = [
        "/path-to-your-theme/in-the-lms-container/my-theme/edx-platform",
    ]
```

2024-07-23 14:15 UTC, magajh commented on README.rst
@bra-i-am I just realized we haven't mentioned anything about the logic behind how this plugin handles and loads the different themes, or the theme hierarchy. Could we add this information, please? I think it's important to explain it so users can understand how it works and how to make the most of it.

2024-07-23 14:21 UTC, bra-i-am commented on README.rst
> +| Redwood          | >= 7.0       |
Although the last version contains some improvements, compatibility with the previous version is not broken :s 

I guess what is lacking is to set the highest and minimum version limits for compatibility in each release, but I don't think that belongs to the effort of this task

Should I set the Redwood version to v7.1.1?

2024-07-23 15:24 UTC, bra-i-am commented on requirements/constraints.txt
> +# Must be the same used in the platform https://raw.githubusercontent.com/openedx/edx-platform/open-release/redwood.master/requirements/constraints.txt
I was using that link as a reference to see the required versions by `edx-platform`.

On the other hand, applying the `common_constraints.txt` file only will replace the constraint `Django<5.0` from the `eox-theming` constraints file... that is why I skip writing it there. However, now that you mention it, I see... the file can be updated and add automatically more needed constraints

2024-07-23 15:30 UTC, bra-i-am commented on requirements/pip-tools.txt
> +    #   -c https://raw.githubusercontent.com/openedx/edx-platform/open-release/redwood.master/requirements/constraints.txt
I included the `redwood.master` constraints before, but @BryanttV made me aware that that file was not necessary. Supposedly that text is autogenerated with the `make upgrade` but I don't really know why that was not modified when I removed the previously mentioned file.

2024-07-23 15:47 UTC, BryanttV commented on README.rst
> +| Redwood          | >= 7.0       |
I say this because `v7.2.0` (formerly `v.7.1.1`) was created mainly to support Redwood, and it is the one that ensures compatibility with this Release.

2024-07-23 16:28 UTC, BryanttV commented on README.rst
> +For example, if you need compatibility for Koa, you can go to the `v2.0.0 README <https://github.com/eduNEXT/eox-theming/blob/v2.0.0/README.rst>`_ to the ``Compatibility Notes`` section; you'll see s
It looks like it used to be a Markdown file 😅.

```suggestion
For example, if you need compatibility for Koa, you can go to the `v2.0.0 README <https://github.com/eduNEXT/eox-theming/blob/v2.0.0/README.md>`_ to the ``Compatibility Notes`` section; you'll see something like this:
```

2024-07-23 18:50 UTC, bra-i-am commented on README.rst
I already added some more paragraphs in the **Overview** where I try to expose the theming process... Please let me know if it is enough or if I'm missing something

thank you c:

2024-07-23 23:02 UTC, mariajgrimaldi reviewed
I left a few minor comments for you to address. Thank you!

2024-07-23 23:02 UTC, mariajgrimaldi commented on requirements/constraints.txt
> +eox-tenant < 12.0.0
I don't think we should add an upper limit to eox-tenat version. This is mainly because we don't know if versions >= 12.x are incompatible with this version of eox-theming, as the constraint suggests. So we'll need to keep updating the constraint over and over. We should add constraints when we know those versions are incompatible with our library, but this is not the case. What do you think?

2024-07-23 23:05 UTC, mariajgrimaldi commented on requirements/constraints.txt
> +eox-tenant < 12.0.0
You can visit other plugins with similar requirements, so we follow the same standard. Here's one: https://github.com/eduNEXT/eox-tagging/blob/master/requirements/base.in#L4

2024-07-24 10:03 UTC, dcoa commented on README.rst
> +    .. code-block:: python
```suggestion
#. Ensure is included the following configuration in `devstack.py` in `eox-theming`:

   .. code-block:: python
```
Could you fix the indentation for the code block?, it is displayed as a note.

2024-07-24 10:07 UTC, dcoa commented on README.rst
> +********
I know that rst does not have a specific hierarchy for titles, but can we use the same one as the other repos?  We are using the sections and below ones https://devguide.python.org/documentation/markup/#sections

2024-07-24 16:12 UTC, BryanttV commented on README.rst
> +#. Compile the before added themes according to you are using a `production environment <https://github.com/eduNEXT/tutor-contrib-edunext-distro/blob/a63e585b9bc3089e00623974c8b365ea874f0a2b/README.m
These links redirect to the code, which is more difficult to understand. What do you think about adding a link to the [private packages section](https://github.com/eduNEXT/tutor-contrib-edunext-distro/blob/master/README.md#private-packages)?

2024-07-24 16:12 UTC, BryanttV commented on README.rst
> +.. |PyPI Badge| image:: https://img.shields.io/pypi/v/eox-theming?label=PyPI
What do you think about adding a Python badge like this? https://img.shields.io/pypi/pyversions/eox-theming.svg :eyes:

2024-07-24 16:22 UTC, BryanttV commented on README.rst
Could we add a license section like this? https://github.com/eduNEXT/eox-tenant?tab=readme-ov-file#license

2024-07-24 21:36 UTC, luisfelipec95 commented
The test cases work as expected.

2024-07-24 21:37 UTC, luisfelipec95 submitted a review, later dismissed
The test cases work as expected.

2024-07-24 23:08 UTC, bra-i-am commented on README.rst
> +#. Compile the before added themes according to you are using a `production environment <https://github.com/eduNEXT/tutor-contrib-edunext-distro/blob/a63e585b9bc3089e00623974c8b365ea874f0a2b/README.m
you are right that is quite clunky my try :v

Instead of linking with private packages that are out of context about what I'm trying to explain, I will write the commands, what do you say?

2024-07-24 23:32 UTC, bra-i-am commented on README.rst
> +.. |PyPI Badge| image:: https://img.shields.io/pypi/v/eox-theming?label=PyPI
yeah... I don't have any issue with it :D

2024-07-25 00:56 UTC, dcoa commented on README.rst
> -**NOTE**: the current ``common.py`` works with Open edX lilac version.
@bra-i-am  thanks for that, can we rewrite this part I feel the information is being duplicated.

You are explaining with a Koa example and after that saying the same with the alert part.

2024-07-25 01:11 UTC, dcoa commented on README.rst
> +
I think this should be removed (or be part of the test cases document).

The reason is that a modification in the `devstack.py` file is a development setting, not for production. Also, in my understanding, the original paragraph has the intention to highlight the following lines  

''suggestion
#. Ensure is included the following configuration in `devstack.py` in `eox-theming`:

   .. code-block:: python

       from lms.envs.common import _make_mako_template_dirs # pylint: disable=import-error
    settings.ENABLE_COMPREHENSIVE_THEMING = True
    settings.COMPREHENSIVE_THEME_DIRS = [
        '/edx/src/themes/ednx-test-themes/edx-platform/',
    ]
    settings.TEMPLATES[1]["DIRS"] = _make_mako_template_dirs
    settings.derive_settings("lms.envs.devstack")

```

Lines that you are including in a previous step.

2024-07-25 01:27 UTC, dcoa commented on README.rst
> +#. Compile the before added themes:
I do not totally agree with this step for:

1. A word is missing in the description 😅 (¿ What should be compiled before adding themes?) I think you want to say (not those words but yeah)
```suggestion
#. Compile the themes after adding it to your instance and before launching:
```
2. We are telling the user to use the launch command because if the instance is configured properly should not do anything at "local". So instead of we can indicate in the installation steps that the plugin should be configured before launching the instance following the Settings section. 

This is more an open question, should we in the usage section describes the production process only?

2024-07-25 12:42 UTC, BryanttV commented on README.rst
> +#. Compile the before added themes according to you are using a `production environment <https://github.com/eduNEXT/tutor-contrib-edunext-distro/blob/a63e585b9bc3089e00623974c8b365ea874f0a2b/README.m
Yes, I'm fine with that

2024-07-25 13:49 UTC, bra-i-am commented on README.rst
> +#. Compile the before added themes:
> 1. A word is missing in the description 😅 (¿ What should be compiled before adding themes?) I think you want to say (not those words but yeah)

I used an inappropriate word, indeed... It should be `previously` instead `before`, but the correction you give sounds better

> ... instead of we can indicate in the installation steps that the plugin should be configured before launching the instance following the Settings section.

I added it as a `Pre-requirement`

> Should we in the **usage** section describe the production process only? In my opinion yes.

Now that you mention it, I think you are right... if we need something for `dev`, we should have internal documentation for that

2024-07-29 12:02 UTC, dcoa commented on README.rst
> +If you are looking for professional development or support with multitenancy or multi-sites in the Open edX platform, you can reach out to sales@edunext.co
I think this line is extra

2024-07-29 23:14 UTC, dcoa commented on README.rst
Sorry @bra-i-am, I just discovered that we are not explaining how to extend the templates with eox-theming, which is also part of the plugin's function to enhance the theming customization.

2024-07-31 19:47 UTC, bra-i-am commented
**UPDATE**
This PR was uploaded to the Redwood stage environment https://tenant-a.redwood.releases.edunext.link/

You should be able to see the environment customized with _bragi_ and the UI of this specific tenant should be consistently colorized with a fuchsia primary color. Additionally, when going to https://tenant-a.redwood.releases.edunext.link/login you should see the alert added in the tenant configs jumping out. 

On the other hand, to test [the fix](https://github.com/eduNEXT/eox-theming/pull/55/files#diff-e5e81b62f9ddf263a53cd1958ab11d2bc9e74943d8fb95ac69d213363ce366c1L96), you should go to the [Wiki of the testing course](https://tenant-a.redwood.releases.edunext.link/courses/course-v1:tenantA+CPTA-001+202407/wiki/tenantA.CPTA-001.202407/) and should be able to see the custom footer defined in the tenant attribute `footer_override`

2024-07-31 23:20 UTC, luisfelipec95 approved these changes

2024-07-31 23:43 UTC, mariajgrimaldi reviewed
A few non-blocking comments. Thanks!

2024-07-31 23:43 UTC, mariajgrimaldi commented on README.rst
Should we do that in the docs file instead? Something similar to what we did here: https://github.com/eduNEXT/eox-hooks/pull/56/files#diff-d55f6f855764483992ed77b185a8571acaacfb796eb1ff1bb2e6ce62f3397300

2024-07-31 23:43 UTC, mariajgrimaldi commented on README.rst
> +                        └── templates
This is not rendering correctly:
![image](https://github.com/user-attachments/assets/c20d9f77-a1e5-4e8a-8e7d-e0f1a618af76)

2024-07-31 23:43 UTC, mariajgrimaldi commented on requirements/constraints.txt
> +pylint<2.16.0
Can we add a comment next to each constraint explaining why it's needed as suggested on top of the file?

2024-08-01 00:47 UTC, dcoa commented
Sorry @bra-i-am,  do you mind updating the links inside the code that points to `edx` to `openedx`?

https://github.com/eduNEXT/eox-theming/blob/2e35f4be0eba8178d6dc8682b88c0e96dd6239e4/eox_theming/settings/common.py#L45

2024-08-01 02:19 UTC, magajh requested changes

2024-08-01 02:19 UTC, magajh commented on requirements/constraints.txt
>  pycodestyle<2.9.0
@bra-i-am, looks like this pycodestyle and the pylint constraints are not necessary. Have we considered upgrading the requirements without them or do we have a specific reason to keep them?

2024-08-01 15:35 UTC, BryanttV commented
Hi @bra-i-am, I was testing in the remote environment, and everything works as expected, thank you!

2024-08-02 16:34 UTC, BryanttV commented on CHANGELOG.md
> +## v7.2.0 - 2024-07-24
We can update the date, please. After that, I will leave my approval

2024-08-02 18:37 UTC, mariajgrimaldi commented on README.rst
Should these documentation efforts be part of a different PR?

2024-08-05 20:36 UTC, magajh approved these changes
LGTM

2024-08-06 00:59 UTC, dcoa approved these changes
Understanding that any additional change in the documentation could be managed in a different PR, I left my approval.

2024-08-06 13:52 UTC, merged